name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Specify Windows runner.

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
 
    # - name: Install PyTest Package
    #   uses: pip install pytest

#To install dependencies.
    # - name: Install dependencies
    #   run: pip install -r requirements.txt  # If you have any dependencies.

    - name: make install
      run: make install

#    - name: Install dependencies
#      run: pip install -r requirements.txt  # If you have any dependencies.

    - name: Run tests
      run: python -m unittest test_main.py
