name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Specify Windows runner.

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Update to Node.js version 16.

#    - name: Install dependencies
#      run: pip install -r requirements.txt  # If you have any dependencies.

    - name: Run tests
      run: python -m unittest test_main.py
