name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Specify Windows runner.

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install PyTest Package
      run: pip install pytest

    - name: Install dependencies
      run: pip install -r requirements.txt  # If you have any dependencies.

    - name: build application
      run: make build

    - name: Run tests
      run: pytest test_main.py
      